# Generated by Django 4.2.6 on 2023-11-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('subtitulo', models.CharField(max_length=32)),
                ('cuerpo', models.CharField(max_length=1200)),
                ('autor', models.CharField(max_length=32)),
                ('fecha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=32)),
                ('modelo', models.CharField(max_length=32)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=32)),
                ('modelo', models.CharField(max_length=32)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sedan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=32)),
                ('modelo', models.CharField(max_length=32)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SUV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=32)),
                ('modelo', models.CharField(max_length=32)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
