# Generated by Django 4.2.6 on 2023-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_rodados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
