# Generated by Django 4.2.6 on 2023-11-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_rodados', '0003_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatares/'),
        ),
    ]
