# Generated by Django 4.2.6 on 2023-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_rodados', '0004_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='compacto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatares/'),
        ),
    ]
